$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
useGitignore: true
files:
  - '**'
  - .*
  - .*/**
  - '!.git/**'
ignorePaths:
  - pnpm-lock.yaml
dictionaries:
  - npm
  - softwareTerms
  - fullstack
  - html
  - css
  - redis
import:
  - '@cspell/dict-redis/cspell-ext.json'
words:
  - aceternity
  - airpods
  - anishde
  - antec
  - argb
  - asus
  - beamer
  - benoit
  - bentogrids
  - bowser
  - bradlc
  - cleanshot
  - cmdk
  - cobe
  - colm
  - customizer
  - dbaeumer
  - delba
  - dotenvx
  - duarte
  - eihab
  - embla
  - evilrabbit
  - fuma
  - fumadocs
  - ghostty
  - gifs
  - googleusercontent
  - hiett
  - iina
  - innerhtml
  - jahir
  - joshwcomeau
  - jsxs
  - karabiner
  - keka
  - keychron
  - leerob
  - linktree
  - macbook
  - maximeheckel
  - maxleiter
  - motrix
  - nelsonlai
  - nelsonlaidev
  - nerdfish
  - nextdotjs
  - nikolovlazar
  - nodedotjs
  - nosniff
  - noto
  - nums
  - nuqs
  - oliveira
  - orbstack
  - orpc
  - paralleldrive
  - pathnames
  - peduarte
  - planetscale
  - plpgsql
  - posthog
  - prefs
  - presigner
  - radixui
  - reactquery
  - reqwest
  - rmiz
  - ryzen
  - sameorigin
  - samuelkraft
  - scoutly
  - shadcn
  - shiki
  - shikijs
  - simulately
  - sonarjs
  - techstack
  - theodorusclarence
  - timebombs
  - tsvector
  - tuite
  - turbopack
  - turborepo
  - umami
  - unifiedjs
  - unsub
  - unzoom
  - vaul
  - vocs
  - waka
  - wakatime
  - zenorocha
